# Generated by Django 3.0.5 on 2026-02-09 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_auto_20201015_2036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-appointmentDate']},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='patientdischargedetails',
            options={'ordering': ['-releaseDate'], 'verbose_name_plural': 'Patient Discharge Details'},
        ),
    ]
