# Generated by Django 3.0.5 on 2026-02-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0020_auto_20260210_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('Dermatologist', 'Dermatologist'), ('Emergency Medicine', 'Emergency Medicine'), ('Allergist', 'Allergist'), ('Anesthesiologist', 'Anesthesiologist'), ('Colon & Rectal Surgeon', 'Colon & Rectal Surgeon')], default='Cardiologist', max_length=50),
        ),
    ]
