# Generated by Django 3.0.5 on 2026-02-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0021_auto_20260210_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='consultationDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='consultationNotes',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='consultationTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientdischargedetails',
            name='canReapply',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='patientdischargedetails',
            name='followUpNotes',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('Dermatologists', 'Dermatologists'), ('Emergency Medicine Specialists', 'Emergency Medicine Specialists'), ('Allergists/Immunologists', 'Allergists/Immunologists'), ('Anesthesiologists', 'Anesthesiologists'), ('Colon and Rectal Surgeons', 'Colon and Rectal Surgeons')], default='Cardiologist', max_length=50),
        ),
    ]
