# Generated by Django 3.0.5 on 2026-03-02 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0022_auto_20260211_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointmentDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('Dermatology', 'Dermatology'), ('Emergency Medicine', 'Emergency Medicine'), ('ENT', 'ENT'), ('Gastroenterology', 'Gastroenterology'), ('General Medicine', 'General Medicine'), ('Neurology', 'Neurology'), ('Orthopedics', 'Orthopedics'), ('Pediatrics', 'Pediatrics'), ('Pulmonology', 'Pulmonology'), ('Urology', 'Urology')], default='Cardiologist', max_length=50),
        ),
    ]
